add_newline = false
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($container$fill \n)\
${custom.proxy}\
$directory\
$git_branch\
$git_metrics\
$git_commit\
$git_state\
$git_status\
$custom\
$status\
\n$character"""

[fill]
symbol = ' '

[custom.proxy]
disabled = false
shell = ["bash"]
when = 'test -n "$https_proxy"'
symbol = " "
style = "fg:#ffffff"
format = '[ $symbol]($style)'

[character]
format = "[▶](bold italic #F6C99F) "
vicmd_symbol = "[N] >>>"

[directory]
home_symbol = "~"
truncation_length = 10
truncation_symbol = "../"
truncate_to_repo = true
read_only = " ◈"
use_os_path_sep = true
style = "#B1FCE5"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold #B1FCE5'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
fish_style_pwd_dir_length = 0

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
symbol = "[△](bold italic #F6C99F)"
style = "italic #F6C99F"
only_attached = true

[git_metrics]
format = ' ([+$added]($added_style))([-$deleted]($deleted_style)) '
added_style = 'bold green'
deleted_style = 'bold red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic #B1FCE5"
format = "([$ahead_behind]($style))"
ahead = "[▴[${count}](bold green)](green)"
behind = "[▿[${count}](bold red)](red)"

[package]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[nix_shell]
disabled = true

[localip]
disabled = true
