# [ ](#ffffff)\
format = """
[](#000000)\
[󰛹](fg:#fafafa bg:#000000)\
$username\
$directory\
${custom.proxy}\
$git_branch\
$git_status\
$git_metrics\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nim\
$rust\
$time\
[](fg:#000000)\
\n
"""

# Disable the blank line at the start of the prompt
# add_newline = true

[custom.proxy]
command = 'echo "(proxy)"'
when = ''' test $http_proxy != "" '''
# symbol = "󱞩"
style = "fg:#bae6fd bg:#000000"
format = '[$symbol $output]($style)'

[package]
style = "fg:#fafafa bg:#000000"
symbol = "\ue5fa "
format = "[ $version ]($style)"
display_private = true

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = false

[directory]
style = "bold fg:#fafafa bg:#000000"
format = "[ $path]($style)"
truncation_length = 10
truncation_symbol = "../"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~/code/sr/stil" = " "
"~/code/sr/webben" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[git_branch]
symbol = "  "
style = "bold #fafafa bg:#000000"
format = '[ $symbol$branch(:$remote_branch) ]($style)'
# format = '[[on $symbol $branch ](fg:#000)]($style)'

[git_status]
style = "bold #fafafa bg:#000000"
ahead = "⇡"
diverged = "⇕⇡⇣"
behind = "⇣"
format = '[($ahead_behind)()]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[nodejs]
disabled = false
symbol = ""
style = "bold 149"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
# style = "bg:#33658A"
format = '[[  $time ]()]($style)'
