-- custom theme based on Vesper
-- generated by AI from https://github.com/bdsqqq/vesper-zed/blob/main/themes/vesper-dark.json

local M = {}

local palettes = {
	dark = {
		bg = "#101010",
		bg_elevated = "#1A1A1A",
		bg_highlight = "#161616",
		bg_visual = "#473a2f",
		bg_selection = "#232323",
		fg = "#FFFFFF",
		fg_muted = "#A0A0A0",
		fg_dim = "#7E7E7E",
		fg_gutter = "#505050",
		accent = "#FFC799",
		string = "#99FFE4",
		comment = "#8b8b8b",
		error = "#FF8080",
		warning = "#FFC799",
		info = "#7E7E7E",
		success = "#99FFE4",
		border = "#101010",
		scrollbar = "#343434",
		search = "#575757",
		-- Terminal colors
		black = "#101010",
		bright_black = "#7E7E7E",
		red = "#f5a191",
		bright_red = "#ff8080",
		green = "#90b99f",
		bright_green = "#99FFE4",
		yellow = "#e6b99d",
		bright_yellow = "#FFC799",
		blue = "#aca1cf",
		bright_blue = "#b9aeda",
		magenta = "#e29eca",
		bright_magenta = "#ecaad6",
		cyan = "#ea83a5",
		bright_cyan = "#f591b2",
		white = "#A0A0A0",
		bright_white = "#ffffff",
	},
	light = {
		bg = "#FFFFFF",
		bg_elevated = "#FAFAFA",
		bg_highlight = "#F7F7F7",
		bg_visual = "#F2F2F2",
		bg_selection = "#EDEDED",
		fg = "#1A1A1A",
		fg_muted = "#555555",
		fg_dim = "#808080",
		fg_gutter = "#C0C0C0",
		accent = "#E0A96D",
		string = "#00A88B",
		comment = "#B5B5B5",
		error = "#E57373",
		warning = "#FFC107",
		info = "#757575",
		success = "#4CAF50",
		border = "#EDEDED",
		scrollbar = "#CFCFCF",
		search = "#FFF5EB",
		-- Terminal colors
		black = "#333333",
		bright_black = "#A1A1A1",
		red = "#E57373",
		bright_red = "#EF5350",
		green = "#66BB6A",
		bright_green = "#81C784",
		yellow = "#FFB74D",
		bright_yellow = "#FFD54F",
		blue = "#64B5F6",
		bright_blue = "#42A5F5",
		magenta = "#F48FB1",
		bright_magenta = "#EC407A",
		cyan = "#80DEEA",
		bright_cyan = "#4DD0E1",
		white = "#BDBDBD",
		bright_white = "#FFFFFF",
	},
}

local function set_highlights(p)
	local hl = vim.api.nvim_set_hl
	local mix = M.mix

	-- Editor
	hl(0, "Normal", { fg = p.fg, bg = "NONE" })
	hl(0, "NormalFloat", { fg = p.fg, bg = p.bg_elevated })
	hl(0, "FloatBorder", { fg = p.fg_muted, bg = p.bg_elevated })
	hl(0, "Cursor", { fg = p.bg, bg = p.accent })
	hl(0, "CursorLine", { bg = "#101212" })
	hl(0, "CursorColumn", { bg = p.bg_highlight })
	hl(0, "ColorColumn", { bg = p.bg_elevated })
	hl(0, "LineNr", { fg = p.fg_gutter })
	hl(0, "CursorLineNr", { fg = p.fg, bold = true })
	hl(0, "SignColumn", { fg = p.fg_gutter, bg = p.bg })
	hl(0, "VertSplit", { fg = p.border })
	hl(0, "WinSeparator", { fg = p.border })
	hl(0, "Folded", { fg = p.fg_muted, bg = p.bg_elevated })
	hl(0, "FoldColumn", { fg = p.fg_gutter, bg = p.bg })
	hl(0, "NonText", { fg = p.fg_gutter })
	hl(0, "SpecialKey", { fg = p.fg_dim })
	hl(0, "Whitespace", { fg = p.fg_gutter })
	hl(0, "EndOfBuffer", { fg = p.bg })

	-- Search
	hl(0, "Search", { fg = p.fg, bg = p.search })
	hl(0, "IncSearch", { fg = p.bg, bg = p.accent })
	hl(0, "CurSearch", { fg = p.bg, bg = p.accent })
	hl(0, "Substitute", { fg = p.bg, bg = p.error })

	-- Selection
	hl(0, "Visual", { bg = p.bg_visual })
	hl(0, "VisualNOS", { bg = p.bg_visual })

	-- Statusline & Tabline
	hl(0, "StatusLine", { fg = p.fg, bg = p.bg })
	hl(0, "StatusLineNC", { fg = p.fg_muted, bg = p.bg })
	hl(0, "TabLine", { fg = p.fg_muted, bg = p.bg })
	hl(0, "TabLineFill", { bg = p.bg })
	hl(0, "TabLineSel", { fg = p.fg, bg = p.bg_highlight })
	hl(0, "WinBar", { fg = p.fg, bg = p.bg })
	hl(0, "WinBarNC", { fg = p.fg_muted, bg = p.bg })

	-- Pmenu
	hl(0, "Pmenu", { fg = p.fg, bg = p.bg_elevated })
	hl(0, "PmenuSel", { fg = p.fg, bg = p.bg_selection })
	hl(0, "PmenuSbar", { bg = p.bg_elevated })
	hl(0, "PmenuThumb", { bg = p.scrollbar })

	-- Messages
	hl(0, "ModeMsg", { fg = p.fg, bold = true })
	hl(0, "MoreMsg", { fg = p.string })
	hl(0, "Question", { fg = p.string })
	hl(0, "WarningMsg", { fg = p.warning })
	hl(0, "ErrorMsg", { fg = p.error })

	-- Diff
	hl(0, "DiffAdd", { bg = "#1E3B33" })
	hl(0, "DiffChange", { bg = "#3D2D1E" })
	hl(0, "DiffDelete", { bg = "#3D1E1E" })
	hl(0, "DiffText", { bg = "#5C4530" })
	hl(0, "diffAdded", { fg = p.success })
	hl(0, "diffRemoved", { fg = p.error })
	hl(0, "diffChanged", { fg = p.warning })

	-- Spelling
	hl(0, "SpellBad", { undercurl = true, sp = p.error })
	hl(0, "SpellCap", { undercurl = true, sp = p.warning })
	hl(0, "SpellLocal", { undercurl = true, sp = p.info })
	hl(0, "SpellRare", { undercurl = true, sp = p.info })

	-- Misc
	hl(0, "MatchParen", { fg = p.accent, bold = true })
	hl(0, "Directory", { fg = p.accent })
	hl(0, "Title", { fg = p.accent, bold = true })
	hl(0, "Conceal", { fg = p.fg_dim })
	hl(0, "QuickFixLine", { bg = p.bg_selection })

	-- Syntax (legacy vim groups)
	hl(0, "Comment", { fg = p.comment, italic = true })
	hl(0, "Constant", { fg = p.accent })
	hl(0, "String", { fg = p.string })
	hl(0, "Character", { fg = p.string })
	hl(0, "Number", { fg = p.accent })
	hl(0, "Boolean", { fg = p.fg })
	hl(0, "Float", { fg = p.accent })
	hl(0, "Identifier", { fg = p.fg_muted })
	hl(0, "Function", { fg = p.accent })
	hl(0, "Statement", { fg = p.fg_muted })
	hl(0, "Conditional", { fg = p.fg_muted })
	hl(0, "Repeat", { fg = p.fg_muted })
	hl(0, "Label", { fg = p.fg })
	hl(0, "Operator", { fg = p.fg_muted })
	hl(0, "Keyword", { fg = p.fg_muted })
	hl(0, "Exception", { fg = p.fg_muted })
	hl(0, "PreProc", { fg = p.fg_muted })
	hl(0, "Include", { fg = p.fg_muted })
	hl(0, "Define", { fg = p.fg_muted })
	hl(0, "Macro", { fg = p.accent })
	hl(0, "PreCondit", { fg = p.fg_muted })
	hl(0, "Type", { fg = p.accent })
	hl(0, "StorageClass", { fg = p.fg_muted })
	hl(0, "Structure", { fg = p.accent })
	hl(0, "Typedef", { fg = p.accent })
	hl(0, "Special", { fg = p.fg_muted })
	hl(0, "SpecialChar", { fg = p.accent })
	hl(0, "Tag", { fg = p.accent })
	hl(0, "Delimiter", { fg = p.fg_muted })
	hl(0, "SpecialComment", { fg = p.comment })
	hl(0, "Debug", { fg = p.warning })
	hl(0, "Underlined", { underline = true })
	hl(0, "Ignore", { fg = p.fg_dim })
	hl(0, "Error", { fg = p.error })
	hl(0, "Todo", { fg = p.bg, bg = p.accent, bold = true })

	-- Treesitter
	hl(0, "@variable", { fg = p.fg })
	hl(0, "@variable.builtin", { fg = p.fg_muted })
	hl(0, "@variable.parameter", { fg = p.fg })
	hl(0, "@variable.member", { fg = p.fg })
	hl(0, "@constant", { fg = p.accent })
	hl(0, "@constant.builtin", { fg = p.accent })
	hl(0, "@constant.macro", { fg = p.accent })
	hl(0, "@module", { fg = p.fg })
	hl(0, "@label", { fg = p.accent })
	hl(0, "@string", { fg = p.string })
	hl(0, "@string.escape", { fg = p.accent })
	hl(0, "@string.regex", { fg = p.string })
	hl(0, "@string.special", { fg = p.string })
	hl(0, "@character", { fg = p.string })
	hl(0, "@character.special", { fg = p.accent })
	hl(0, "@boolean", { fg = p.accent })
	hl(0, "@number", { fg = p.accent })
	hl(0, "@number.float", { fg = p.accent })
	hl(0, "@type", { fg = p.accent })
	hl(0, "@type.builtin", { fg = p.accent })
	hl(0, "@type.definition", { fg = p.accent })
	hl(0, "@attribute", { fg = p.fg_muted })
	hl(0, "@property", { fg = p.fg })
	hl(0, "@function", { fg = p.accent })
	hl(0, "@function.builtin", { fg = p.accent })
	hl(0, "@function.call", { fg = p.accent })
	hl(0, "@function.macro", { fg = p.accent })
	hl(0, "@function.method", { fg = p.accent })
	hl(0, "@function.method.call", { fg = p.accent })
	hl(0, "@constructor", { fg = p.accent })
	hl(0, "@operator", { fg = p.fg_muted })

	-- Keywords (all grey)
	hl(0, "@keyword", { fg = p.fg_muted })
	hl(0, "@keyword.conditional", { fg = p.fg_muted })
	hl(0, "@keyword.conditional.ternary", { fg = p.fg_muted })
	hl(0, "@keyword.coroutine", { fg = p.fg_muted })
	hl(0, "@keyword.debug", { fg = p.fg_muted })
	hl(0, "@keyword.directive", { fg = p.fg_muted })
	hl(0, "@keyword.directive.define", { fg = p.fg_muted })
	hl(0, "@keyword.exception", { fg = p.fg_muted })
	hl(0, "@keyword.function", { fg = p.fg_muted })
	hl(0, "@keyword.import", { fg = p.fg_muted })
	hl(0, "@keyword.export", { fg = p.fg_muted })
	hl(0, "@keyword.operator", { fg = p.fg_muted })
	hl(0, "@keyword.repeat", { fg = p.fg_muted })
	hl(0, "@keyword.return", { fg = p.fg_muted })
	hl(0, "@keyword.storage", { fg = p.fg_muted })
	hl(0, "@keyword.type", { fg = p.fg_muted })

	-- Punctuation
	hl(0, "@punctuation.delimiter", { fg = p.fg_muted })
	hl(0, "@punctuation.bracket", { fg = p.fg_muted })
	hl(0, "@punctuation.special", { fg = p.fg_muted })

	-- Comments
	hl(0, "@comment", { fg = p.comment, italic = true })
	hl(0, "@comment.documentation", { fg = p.comment, italic = true })
	hl(0, "@comment.error", { fg = p.error })
	hl(0, "@comment.warning", { fg = p.warning })
	hl(0, "@comment.todo", { fg = p.bg, bg = p.accent })
	hl(0, "@comment.note", { fg = p.info })

	-- Markup
	hl(0, "@markup.heading", { fg = p.accent, bold = true })
	hl(0, "@markup.strong", { bold = true })
	hl(0, "@markup.italic", { italic = true })
	hl(0, "@markup.strikethrough", { strikethrough = true })
	hl(0, "@markup.underline", { underline = true })
	hl(0, "@markup.quote", { fg = p.fg_muted, italic = true })
	hl(0, "@markup.math", { fg = p.accent })
	hl(0, "@markup.link", { fg = p.fg })
	hl(0, "@markup.link.url", { fg = p.string, underline = true })
	hl(0, "@markup.raw", { fg = p.string })
	hl(0, "@markup.list", { fg = p.fg_muted })

	-- Tags (JSX/HTML)
	hl(0, "@tag", { fg = p.accent })
	hl(0, "@tag.builtin", { fg = p.accent })
	hl(0, "@tag.attribute", { fg = p.fg_muted })
	hl(0, "@tag.delimiter", { fg = p.fg_muted })

	-- LSP Semantic Tokens
	hl(0, "@lsp.type.class", { fg = p.accent })
	hl(0, "@lsp.type.decorator", { fg = p.accent })
	hl(0, "@lsp.type.enum", { fg = p.accent })
	hl(0, "@lsp.type.enumMember", { fg = p.accent })
	hl(0, "@lsp.type.function", { fg = p.accent })
	hl(0, "@lsp.type.interface", { fg = p.accent })
	hl(0, "@lsp.type.macro", { fg = p.accent })
	hl(0, "@lsp.type.method", { fg = p.accent })
	hl(0, "@lsp.type.namespace", { fg = p.fg })
	hl(0, "@lsp.type.parameter", { fg = p.fg })
	hl(0, "@lsp.type.property", { fg = p.fg })
	hl(0, "@lsp.type.struct", { fg = p.accent })
	hl(0, "@lsp.type.type", { fg = p.accent })
	hl(0, "@lsp.type.typeParameter", { fg = p.accent })
	hl(0, "@lsp.type.variable", { fg = p.fg })

	-- LSP Semantic Token Modifiers (for imports)
	hl(0, "@lsp.typemod.function.defaultLibrary", { fg = p.accent })
	hl(0, "@lsp.typemod.variable.defaultLibrary", { fg = p.fg_muted })
	hl(0, "@lsp.typemod.class.defaultLibrary", { fg = p.accent })

	-- Diagnostics
	hl(0, "DiagnosticError", { fg = p.error })
	hl(0, "DiagnosticWarn", { fg = p.warning })
	hl(0, "DiagnosticInfo", { fg = p.info })
	hl(0, "DiagnosticHint", { fg = p.fg_muted })
	hl(0, "DiagnosticOk", { fg = p.success })
	hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = p.error })
	hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = p.warning })
	hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = p.info })
	hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = p.fg_muted })
	hl(0, "DiagnosticVirtualTextError", { fg = p.error, bg = "#1F1616" })
	hl(0, "DiagnosticVirtualTextWarn", { fg = p.warning, bg = "#1F1B16" })
	hl(0, "DiagnosticVirtualTextInfo", { fg = "#a0a0a0", bg = "#1B1B1B" })
	hl(0, "DiagnosticVirtualTextHint", { fg = "#a0a0a0", bg = "#1C1C1C" })

	-- Git Signs
	hl(0, "GitSignsAdd", { fg = p.success })
	hl(0, "GitSignsChange", { fg = p.warning })
	hl(0, "GitSignsDelete", { fg = p.error })
	hl(0, "GitSignsCurrentLineBlame", { fg = "#a0a0a0" })

	-- Telescope
	hl(0, "TelescopeNormal", { fg = p.fg, bg = p.bg_elevated })
	hl(0, "TelescopeBorder", { fg = p.fg_muted, bg = p.bg_elevated })
	hl(0, "TelescopePromptNormal", { fg = p.fg, bg = p.bg_elevated })
	hl(0, "TelescopePromptBorder", { fg = p.fg_muted, bg = p.bg_elevated })
	hl(0, "TelescopePromptTitle", { fg = p.bg, bg = p.accent })
	hl(0, "TelescopePreviewTitle", { fg = p.bg, bg = p.success })
	hl(0, "TelescopeResultsTitle", { fg = p.bg_elevated, bg = p.bg_elevated })
	hl(0, "TelescopeSelection", { bg = p.bg_selection })
	hl(0, "TelescopeMatching", { fg = p.accent, bold = true })

	-- nvim-cmp
	hl(0, "CmpItemAbbr", { fg = p.fg })
	hl(0, "CmpItemAbbrMatch", { fg = p.accent, bold = true })
	hl(0, "CmpItemAbbrMatchFuzzy", { fg = p.accent, bold = true })
	hl(0, "CmpItemAbbrDeprecated", { fg = p.fg_dim, strikethrough = true })
	hl(0, "CmpItemKind", { fg = p.fg_muted })
	hl(0, "CmpItemMenu", { fg = p.fg_dim })

	-- nvim-tree / neo-tree
	hl(0, "NvimTreeNormal", { fg = p.fg, bg = p.bg })
	hl(0, "NvimTreeRootFolder", { fg = p.accent, bold = true })
	hl(0, "NvimTreeFolderIcon", { fg = p.accent })
	hl(0, "NvimTreeFolderName", { fg = p.fg })
	hl(0, "NvimTreeOpenedFolderName", { fg = p.accent })
	hl(0, "NvimTreeGitDirty", { fg = p.warning })
	hl(0, "NvimTreeGitNew", { fg = p.success })
	hl(0, "NvimTreeGitDeleted", { fg = p.error })
	hl(0, "NeoTreeNormal", { fg = p.fg, bg = p.bg })
	hl(0, "NeoTreeNormalNC", { fg = p.fg, bg = p.bg })

	-- Indent Blankline
	hl(0, "IblIndent", { fg = p.bg_visual })
	hl(0, "IblScope", { fg = p.fg_gutter })

	-- Which-key
	hl(0, "WhichKey", { fg = p.accent })
	hl(0, "WhichKeyGroup", { fg = p.fg_muted })
	hl(0, "WhichKeyDesc", { fg = p.fg })
	hl(0, "WhichKeySeparator", { fg = p.fg_dim })

	-- Lazy.nvim
	hl(0, "LazyH1", { fg = p.bg, bg = p.accent, bold = true })
	hl(0, "LazyButton", { fg = p.fg, bg = p.bg_visual })
	hl(0, "LazyButtonActive", { fg = p.bg, bg = p.accent })

	-- Notify
	hl(0, "NotifyERRORBorder", { fg = p.error })
	hl(0, "NotifyWARNBorder", { fg = p.warning })
	hl(0, "NotifyINFOBorder", { fg = p.info })
	hl(0, "NotifyDEBUGBorder", { fg = p.fg_dim })
	hl(0, "NotifyTRACEBorder", { fg = p.fg_dim })
	hl(0, "NotifyERRORIcon", { fg = p.error })
	hl(0, "NotifyWARNIcon", { fg = p.warning })
	hl(0, "NotifyINFOIcon", { fg = p.info })
	hl(0, "NotifyDEBUGIcon", { fg = p.fg_dim })
	hl(0, "NotifyTRACEIcon", { fg = p.fg_dim })
	hl(0, "NotifyERRORTitle", { fg = p.error })
	hl(0, "NotifyWARNTitle", { fg = p.warning })
	hl(0, "NotifyINFOTitle", { fg = p.info })
	hl(0, "NotifyDEBUGTitle", { fg = p.fg_dim })
	hl(0, "NotifyTRACETitle", { fg = p.fg_dim })

	-- TypeScript
	hl(0, "typescriptIdentifierName", { fg = p.accent })
	hl(0, "typescriptTypeBlock", { fg = p.accent })
	hl(0, "typescriptBraces", { fg = p.fg_muted })
	hl(0, "javascriptBraces", { fg = p.fg_muted })
	hl(0, "javascriptParens", { fg = p.fg_muted })
	hl(0, "typescriptArrowFuncDef", { fg = p.fg_muted })
	hl(0, "typescriptTypeAnnotation", { fg = p.fg_muted })
	hl(0, "typescriptParens", { fg = p.fg_muted })
	hl(0, "typescriptArrowFunc", { fg = p.fg_muted })
	hl(0, "typescriptAssign", { fg = p.fg_muted })
	hl(0, "htmlTag", { fg = p.fg_muted })
	hl(0, "htmlTagName", { fg = p.accent })
	hl(0, "typescriptParenExp", { fg = p.fg_muted })
	hl(0, "tsxAttrib", { fg = p.fg_muted })
	hl(0, "tsxEqual", { fg = p.fg_muted })
	hl(0, "typescriptTemplateSB", { fg = p.fg_muted })
	hl(0, "typescriptTernaryOp", { fg = p.fg_muted })
	hl(0, "typescriptBinaryOp", { fg = p.fg_muted })

	-- Terminal colors
	vim.g.terminal_color_0 = p.black
	vim.g.terminal_color_1 = p.red
	vim.g.terminal_color_2 = p.green
	vim.g.terminal_color_3 = p.yellow
	vim.g.terminal_color_4 = p.blue
	vim.g.terminal_color_5 = p.magenta
	vim.g.terminal_color_6 = p.cyan
	vim.g.terminal_color_7 = p.white
	vim.g.terminal_color_8 = p.bright_black
	vim.g.terminal_color_9 = p.bright_red
	vim.g.terminal_color_10 = p.bright_green
	vim.g.terminal_color_11 = p.bright_yellow
	vim.g.terminal_color_12 = p.bright_blue
	vim.g.terminal_color_13 = p.bright_magenta
	vim.g.terminal_color_14 = p.bright_cyan
	vim.g.terminal_color_15 = p.bright_white
end

function M.setup(opts)
	opts = opts or {}
	local variant = opts.variant or "dark"

	vim.cmd("hi clear")
	if vim.fn.exists("syntax_on") then
		vim.cmd("syntax reset")
	end

	vim.o.termguicolors = true
	vim.g.colors_name = "vesper"

	local palette = palettes[variant] or palettes.dark
	set_highlights(palette)
end

return M
